name: photo_box
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0' # Sesuaikan dengan versi SDK Anda

dependencies:
  flutter:
    sdk: flutter

  # --- VERSI DIPERBARUI ---
  camera: ^0.11.3
  screenshot: ^3.0.0
  # ------------------------

  # Dependensi lain dari proyek Anda
  path_provider: ^2.0.12 # (Versi ini masih OK, tidak ada di daftar outdated)
  image: ^4.1.3          # (Versi ini masih OK)
  
  # Dependensi yang kita tambahkan untuk fitur
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  blue_thermal_printer: ^1.2.2 # (Sudah versi terbaru)

  # Default
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- VERSI DIPERBARUI ---
  flutter_lints: ^6.0.0
  # ------------------------

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
