name: photo_box
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0' # Sesuaikan dengan versi SDK Anda

dependencies:
  flutter:
    sdk: flutter

  # --- VERSI DIPERBARUI ---
  camera: ^0.11.3
  screenshot: ^3.0.0
  # ------------------------

  # Dependensi lain dari proyek Anda
  path_provider: ^2.0.12 
  image: ^4.1.3          
  
  # Dependensi yang kita tambahkan untuk fitur
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  
  # --- PAKET PRINTER YANG SEHARUSNYA DIGUNAKAN ---
  # (print_bluetooth_thermal dihapus karena kode kita menggunakan flutter_blue_plus)
  flutter_blue_plus: ^1.31.22 # <-- BARU: Ini diperlukan untuk Bluetooth
  esc_pos_utils_plus: ^2.0.4

  # --- PAKET UNTUK CETAK PDF ---
  printing: ^5.14.0  # <-- BARU: Ini diperlukan untuk preview cetak PDF
  pdf: ^3.10.8       # <-- BARU: Ini diperlukan untuk membuat file PDF
  # -----------------------------

  # Default
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- VERSI DIPERBARUI ---
  flutter_lints: ^6.0.0
  # ------------------------

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700