name: photo_box
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0' # Sesuaikan dengan versi SDK Anda

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  screenshot: ^3.0.0
  path_provider: ^2.0.12 
  image: ^4.1.3          
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.2
  flutter_blue_plus: ^1.31.22 
  esc_pos_utils_plus: ^2.0.4
  # Untuk koneksi ke printer
  print_bluetooth_thermal: ^1.1.0 
  # Untuk manajemen permission (opsional tapi disarankan)
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2

  
  printing: ^5.14.0  
  pdf: ^3.10.8      

  # Default
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- VERSI DIPERBARUI ---
  flutter_lints: ^6.0.0
  # ------------------------

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700